/*

	TODO: Add all includes here.

*/

int PACKAGESIZE_MAX = 65535;

char DATA_ACK_VSERVER[] = {1}; 
char DATA_PACKAGE[PACKAGESIZE_MAX];
char DATA_PACKAGE_INFO[PACKAGESIZE_MAX];

Location HOST_EMBPC;
Location HOST_MABXII;
Location HOST_VSERVER;

int LOCAL_TIMESTAMP;
char MSG_INFO_REQUEST[] = {96};
char MSG_READY[] = {144};
int PACKAGE_COUNTER;
int TIME_THRESHOLD;

char VEC_COMMA[PACKAGESIZE_MAX];
int VEC_COMMA_SIZE;
char VEC_DATATYPES[PACKAGESIZE_MAX];
int VEC_DATATYPES_SIZE;
char VEC_LAYOUT[PACKAGESIZE_MAX];
int VEC_LAYOUT_SIZE;